import { ProjectCards } from '../components/project-cards';
import { ArrowDown, ArrowUpRight, Database, PanelsTopLeft, Mail } from 'lucide-react';

const technologies = ['Java', 'Spring Boot', 'Oracle / PL-SQL', 'JavaScript', 'HTML5 / CSS3', 'PrimeFaces', 'JSF / JSP', 'JUnit / Mockito', 'Python', 'Figma', 'Desarrollo asistido por IA'];
const experience = [
  {company:'Praxis TI',role:'Desarrollador de Software Java',date:'Jun. 2023 — Actualidad',place:'Remoto · México',text:'Modernización y migración de sistemas legacy a Java 11, 21 y 25. Desarrollo de APIs y microservicios, e implementación de interfaces web con PrimeFaces. Creación y optimización de procedimientos almacenados, triggers y funciones en Oracle. Implementación de pruebas unitarias con JUnit y Mockito, elaboración de documentación técnica y análisis de logs para el diagnóstico y la resolución de incidencias.'},
  {company:'Grupo Financiero Inbursa',role:'Desarrollador Backend',date:'Nov. 2022 — Mar. 2023',place:'Pachuca de Soto, Hidalgo',text:'Desarrollo y mantenimiento de aplicaciones backend con Java y Spring Boot, implementando lógica de negocio e integrando funcionalidades en sistemas del sector financiero. Creación y optimización de procedimientos almacenados en Oracle mediante PL/SQL para el procesamiento y acceso a datos. Colaboración con el equipo de desarrollo bajo Scrum para la implementación y el mantenimiento de los requerimientos del proyecto.'},
  {company:'Freelance',role:'Programador web',date:'Feb. 2022 — Nov. 2022',place:'Pachuca de Soto, Hidalgo',text:'Diseño y prototipado de interfaces en Figma, y traducción de propuestas visuales a páginas web con HTML5, CSS3 y JavaScript. Maquetación responsiva y desarrollo de interacciones, aplicando principios de accesibilidad para facilitar el uso en distintos tamaños de pantalla. Ejecución de pruebas funcionales y de usabilidad, depuración de errores y optimización de interfaces para mejorar la experiencia de usuario.'}
];
export default function Home() {
  return <>
    <a className="skip" href="#contenido">Saltar al contenido</a>
    <header className="wrap nav"><a href="#" className="brand">Saul Ramos<span> / </span>dev</a><nav aria-label="Principal"><a href="#perfil">Perfil</a><a href="#experiencia">Experiencia</a><a href="#proyectos">Proyectos</a><a href="#contacto">Contacto</a></nav><span className="edition">JAVA & DESARROLLO WEB</span></header>
    <main id="contenido">
      <section className="wrap hero"><div className="eyebrow"><span className="dot"/> SAUL RAMOS SANCHEZ · DESARROLLADOR DE SOFTWARE</div><h1>De la lógica<br/>a la <em>experiencia.</em></h1><div className="hero-bottom"><p>Desarrollo aplicaciones empresariales con Java, Spring Boot y Oracle, y las conecto con interfaces web claras y funcionales.</p><a className="cta" href="#experiencia">Conoce mi trayectoria <ArrowDown size={18}/></a></div><div className="hero-foot"><span>BACKEND SÓLIDO. INTERFACES BIEN PENSADAS.</span><span>MÉXICO ↗</span></div></section>
      <section id="perfil" className="wrap profile"><div><p className="eyebrow">01 / SOBRE MÍ</p><h2>Las dos caras<br/>del software.</h2><p className="education">Ingeniería en Mecatrónica<br/><strong>Instituto Politécnico Nacional</strong><br/>Campus Hidalgo · 2016–2022</p></div><div className="profile-content"><p className="intro">Soy Saul, desarrollador de software con experiencia en aplicaciones empresariales y modernización de sistemas.</p><p>Mi trabajo abarca migración de sistemas legacy, optimización de bases de datos e interfaces web. Me apoyo en pruebas, documentación y colaboración ágil para construir soluciones mantenibles.</p><p>También utilizo herramientas actuales de inteligencia artificial como apoyo en mi trabajo de desarrollo de software.</p><div className="disciplines"><article><PanelsTopLeft/><h3>Frontend</h3><p>Interfaces responsivas con HTML, CSS, JavaScript y PrimeFaces. Del prototipo en Figma a la implementación.</p></article><article><Database/><h3>Backend</h3><p>Aplicaciones con Java y Spring Boot, datos en Oracle y pruebas con JUnit y Mockito.</p></article></div><div className="tech-list" aria-label="Tecnologías de mi experiencia">{technologies.map(t=><span key={t}>{t}</span>)}</div></div></section>
      <section id="experiencia" className="wrap experience"><div className="section-head"><div><p className="eyebrow">02 / TRAYECTORIA</p><h2>Experiencia que construye.</h2></div><span className="pill">DESARROLLO PROFESIONAL</span></div><div className="timeline">{experience.map(job=><article className="job" key={job.company}><div><p className="job-date">{job.date}</p><h3>{job.company}</h3><p className="job-place">{job.place}</p></div><div><h4>{job.role}</h4><p>{job.text}</p></div></article>)}</div></section>
      <section id="proyectos" className="projects"><div className="wrap"><div className="section-head"><div><p className="eyebrow">03 / PROYECTOS PERSONALES</p><h2>Proyectos para explorar.</h2></div><span className="pill">3 PROYECTOS · 3 ARQUITECTURAS</span></div><p className="section-copy">Aplicaciones personales para poner en práctica mi experiencia y compartir sus decisiones técnicas.</p><ProjectCards /></div></section>
      <section id="contacto" className="wrap closing"><p className="eyebrow">04 / CONTACTO</p><h2>Hablemos de tu<br/>siguiente proyecto<span>.</span></h2><p>Para conversar sobre desarrollo de software, colaboración u oportunidades profesionales.</p><div className="contact-links"><a className="cta" href="mailto:saul222sa@hotmail.com"><Mail size={18}/> Escríbeme</a><a className="back" href="https://www.linkedin.com/in/saulramossanchez-7114a8244" target="_blank" rel="noopener noreferrer">LinkedIn <ArrowUpRight size={18}/></a></div><a className="email" href="mailto:saul222sa@hotmail.com">saul222sa@hotmail.com</a></section>
    </main><footer className="wrap footer"><span className="brand">Saul Ramos<span> / </span>dev</span><span>Este portafolio está hecho con React + TypeScript + Tailwind CSS</span></footer>
  </>;
}




